project:
  type: website
  output-dir: docs

website:
  title: "GADO DANZAMA"
  favicon: image/bigfav.png
  navbar:
    logo: image/bigfav.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
  page-footer: 
    #background: dark
    left:
      - "2023, GADO A. Bachir"
    right: 
      - icon: github
        href: https://github.com/Datadoulla
      - icon: linkedin
        href: https://www.linkedin.com/in/doullagado/
format:
  html:
    theme:
      - cosmo
      - styles.scss
      #light: Flatly
      #dark: solar
    #css: styles.css
    toc: true
    page-layout: full



