project:
  type: website
  output-dir: docs

website:
  title: "GADO DANZAMA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: Flatly
      dark: solar
    css: styles.css
    toc: true
    page-layout: full



